/** @type {import('tailwindcss').Config} */
export default {
  // public/gallery.js injects Tailwind classes at runtime — must be scanned or they are purged.
  content: [
    "./src/**/*.{astro,html,js,ts,jsx,tsx}",
    "./public/gallery.js",
    "./public/demo-live.js",
    "./public/demo-support-table.js",
  ],
  /** Classes only appear in public/gallery.js strings; safelist guarantees production CSS. */
  safelist: [
    "gallery-grid",
    "gallery-row",
    "grid",
    "grid-cols-1",
    "sm:grid-cols-2",
    "lg:grid-cols-3",
    "2xl:grid-cols-4",
    "gap-2",
    "sm:gap-2",
    "min-w-0",
    "text-[10px]",
    "text-[11px]",
    "min-h-[1.75rem]",
    "max-h-28",
    "scroll-mt-28",
    "gap-x-4",
    "gap-y-2",
    "gap-y-1",
    "leading-snug",
    "whitespace-pre-wrap",
    "break-all",
    "max-w-full",
    "border-outline/40",
    "border-outline/30",
    "bg-surface-container/90",
    "bg-surface-container/60",
    "bg-white/60",
    "text-on-surface-variant/50",
    "text-orange-400",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#121211",
        "on-surface": "#121211",
        "on-surface-variant": "#5C5C58",
        "surface-container": "#EDEDE9",
        "surface-container-low": "#F3F3EF",
        "surface-container-lowest": "#FFFFFF",
        surface: "#F9F9F6",
        outline: "#E5E5DF",
        "inverse-surface": "#1A1A19",
        "primary-fixed-dim": "#FFB4A4",
        "primary-container": "#1A1A19",
        "on-primary": "#FFFFFF",
        "on-primary-container": "#F9F9F6",
        primary: "#CE4125",
        background: "#F9F9F6",
      },
      fontFamily: {
        headline: ["Crimson Pro", "serif"],
        body: ["DM Sans", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: { DEFAULT: "0px", lg: "0px", xl: "0px", full: "9999px" },
    },
  },
  plugins: [],
};
